# Site settings
title: Angus Maidment
header-img: img/prof.jpg
email: angus@angusmaidment.com
description: "I am Angus Maidment, and this is my site!"
baseurl:
url: "http://www.angusmaidment.com"
twitter_username: KennyLog_ins
github_username:  duncand0nuts
facebook_username:  angusmaidment

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

kramdown:
  input: GFM
